---
  - "5-alpha-reductase inhibitors"
  - "5-aminosalicylates"
  - "5HT3 receptor antagonists"
  - "ACE inhibitors with calcium channel blocking agents"
  - "ACE inhibitors with thiazides"
  - "adamantane antivirals"
  - "adrenal cortical steroids"
  - "adrenal corticosteroid inhibitors"
  - "adrenergic bronchodilators"
  - "agents for hypertensive emergencies"
  - "agents for pulmonary hypertension"
  - "aldosterone receptor antagonists"
  - "alkylating agents"
  - "allergenics"
  - "alpha-glucosidase inhibitors"
  - "alternative medicines"
  - "amebicides"
  - "aminoglycosides"
  - "aminopenicillins"
  - "aminosalicylates"
  - "AMPA receptor antagonists"
  - "amylin analogs"
  - "analgesic combinations"
  - "analgesics"
  - "androgens and anabolic steroids"
  - "angiotensin converting enzyme inhibitors"
  - "angiotensin II inhibitors with calcium channel blockers"
  - "angiotensin II inhibitors with thiazides"
  - "angiotensin receptor blockers"
  - "angiotensin receptor blockers and neprilysin inhibitors"
  - "anorectal preparations"
  - "anorexiants"
  - "antacids"
  - "anthelmintics"
  - "anti-angiogenic ophthalmic agents"
  - "anti-CTLA-4 monoclonal antibodies"
  - "anti-infectives"
  - "antiadrenergic agents (central) with thiazides"
  - "antiadrenergic agents (peripheral) with thiazides"
  - "antiadrenergic agents, centrally acting"
  - "antiadrenergic agents, peripherally acting"
  - "antiandrogens"
  - "antianginal agents"
  - "antiarrhythmic agents"
  - "antiasthmatic combinations"
  - "antibiotics/antineoplastics"
  - "anticholinergic antiemetics"
  - "anticholinergic antiparkinson agents"
  - "anticholinergic bronchodilators"
  - "anticholinergic chronotropic agents"
  - "anticholinergics/antispasmodics"
  - "anticoagulants"
  - "anticonvulsants"
  - "antidepressants"
  - "antidiabetic agents"
  - "antidiabetic combinations"
  - "antidiarrheals"
  - "antidiuretic hormones"
  - "antidotes"
  - "antiemetic/antivertigo agents"
  - "antifungals"
  - "antigonadotropic agents"
  - "antigout agents"
  - "antihistamines"
  - "antihyperlipidemic agents"
  - "antihyperlipidemic combinations"
  - "antihypertensive combinations"
  - "antihyperuricemic agents"
  - "antimalarial agents"
  - "antimalarial combinations"
  - "antimalarial quinolines"
  - "antimetabolites"
  - "antimigraine agents"
  - "antineoplastic detoxifying agents"
  - "antineoplastic interferons"
  - "antineoplastics"
  - "antiparkinson agents"
  - "antiplatelet agents"
  - "antipseudomonal penicillins"
  - "antipsoriatics"
  - "antipsychotics"
  - "antirheumatics"
  - "antiseptic and germicides"
  - "antithyroid agents"
  - "antitoxins and antivenins"
  - "antituberculosis agents"
  - "antituberculosis combinations"
  - "antitussives"
  - "antiviral agents"
  - "antiviral boosters"
  - "antiviral combinations"
  - "antiviral interferons"
  - "anxiolytics, sedatives, and hypnotics"
  - "aromatase inhibitors"
  - "atypical antipsychotics"
  - "azole antifungals"
  - "bacterial vaccines"
  - "barbiturate anticonvulsants"
  - "barbiturates"
  - "BCR-ABL tyrosine kinase inhibitors"
  - "benzodiazepine anticonvulsants"
  - "benzodiazepines"
  - "beta blockers with calcium channel blockers"
  - "beta blockers with thiazides"
  - "beta-adrenergic blocking agents"
  - "beta-lactamase inhibitors"
  - "bile acid sequestrants"
  - "biologicals"
  - "bisphosphonates"
  - "bone morphogenetic proteins"
  - "bone resorption inhibitors"
  - "bronchodilator combinations"
  - "bronchodilators"
  - "calcineurin inhibitors"
  - "calcitonin"
  - "calcium channel blocking agents"
  - "carbamate anticonvulsants"
  - "carbapenems"
  - "carbonic anhydrase inhibitor anticonvulsants"
  - "carbonic anhydrase inhibitors"
  - "cardiac stressing agents"
  - "cardioselective beta blockers"
  - "cardiovascular agents"
  - "catecholamines"
  - "CD20 monoclonal antibodies"
  - "CD30 monoclonal antibodies"
  - "CD33 monoclonal antibodies"
  - "CD52 monoclonal antibodies"
  - "central nervous system agents"
  - "cephalosporins"
  - "cerumenolytics"
  - "CFTR combinations"
  - "CFTR potentiators"
  - "chelating agents"
  - "chemokine receptor antagonist"
  - "chloride channel activators"
  - "cholesterol absorption inhibitors"
  - "cholinergic agonists"
  - "cholinergic muscle stimulants"
  - "cholinesterase inhibitors"
  - "CNS stimulants"
  - "coagulation modifiers"
  - "colony stimulating factors"
  - "contraceptives"
  - "corticotropin"
  - "coumarins and indandiones"
  - "cox-2 inhibitors"
  - "decongestants"
  - "dermatological agents"
  - "diagnostic radiopharmaceuticals"
  - "diarylquinolines"
  - "dibenzazepine anticonvulsants"
  - "digestive enzymes"
  - "dipeptidyl peptidase 4 inhibitors"
  - "diuretics"
  - "dopaminergic antiparkinsonism agents"
  - "drugs used in alcohol dependence"
  - "echinocandins"
  - "EGFR inhibitors"
  - "estrogen receptor antagonists"
  - "estrogens"
  - "expectorants"
  - "factor Xa inhibitors"
  - "fatty acid derivative anticonvulsants"
  - "fibric acid derivatives"
  - "first generation cephalosporins"
  - "fourth generation cephalosporins"
  - "functional bowel disorder agents"
  - "gallstone solubilizing agents"
  - "gamma-aminobutyric acid analogs"
  - "gamma-aminobutyric acid reuptake inhibitors"
  - "gastrointestinal agents"
  - "general anesthetics"
  - "genitourinary tract agents"
  - "GI stimulants"
  - "glucocorticoids"
  - "glucose elevating agents"
  - "glycopeptide antibiotics"
  - "glycoprotein platelet inhibitors"
  - "glycylcyclines"
  - "gonadotropin releasing hormones"
  - "gonadotropin-releasing hormone antagonists"
  - "gonadotropins"
  - "group I antiarrhythmics"
  - "group II antiarrhythmics"
  - "group III antiarrhythmics"
  - "group IV antiarrhythmics"
  - "group V antiarrhythmics"
  - "growth hormone receptor blockers"
  - "growth hormones"
  - "guanylate cyclase-C agonists"
  - "H. pylori eradication agents"
  - "H2 antagonists"
  - "hedgehog pathway inhibitors"
  - "hematopoietic stem cell mobilizer"
  - "heparin antagonists"
  - "heparins"
  - "HER2 inhibitors"
  - "herbal products"
  - "histone deacetylase inhibitors"
  - "hormones"
  - "hormones/antineoplastics"
  - "hydantoin anticonvulsants"
  - "hydrazide derivatives"
  - "illicit (street) drugs"
  - "immune globulins"
  - "immunologic agents"
  - "immunostimulants"
  - "immunosuppressive agents"
  - "impotence agents"
  - "in vivo diagnostic biologicals"
  - "incretin mimetics"
  - "inhaled anti-infectives"
  - "inhaled corticosteroids"
  - "inotropic agents"
  - "insulin"
  - "insulin-like growth factor"
  - "integrase strand transfer inhibitor"
  - "interferons"
  - "interleukin inhibitors"
  - "interleukins"
  - "intravenous nutritional products"
  - "iodinated contrast media"
  - "ionic iodinated contrast media"
  - "iron products"
  - "ketolides"
  - "laxatives"
  - "leprostatics"
  - "leukotriene modifiers"
  - "lincomycin derivatives"
  - "local injectable anesthetics"
  - "loop diuretics"
  - "lung surfactants"
  - "lymphatic staining agents"
  - "lysosomal enzymes"
  - "macrolide derivatives"
  - "macrolides"
  - "magnetic resonance imaging contrast media"
  - "mast cell stabilizers"
  - "medical gas"
  - "meglitinides"
  - "metabolic agents"
  - "methylxanthines"
  - "mineralocorticoids"
  - "minerals and electrolytes"
  - "miscellaneous agents"
  - "miscellaneous analgesics"
  - "miscellaneous antibiotics"
  - "miscellaneous anticonvulsants"
  - "miscellaneous antidepressants"
  - "miscellaneous antidiabetic agents"
  - "miscellaneous antiemetics"
  - "miscellaneous antifungals"
  - "miscellaneous antihyperlipidemic agents"
  - "miscellaneous antihypertensive combinations"
  - "miscellaneous antimalarials"
  - "miscellaneous antineoplastics"
  - "miscellaneous antiparkinson agents"
  - "miscellaneous antipsychotic agents"
  - "miscellaneous antituberculosis agents"
  - "miscellaneous antivirals"
  - "miscellaneous anxiolytics, sedatives and hypnotics"
  - "miscellaneous bone resorption inhibitors"
  - "miscellaneous cardiovascular agents"
  - "miscellaneous central nervous system agents"
  - "miscellaneous coagulation modifiers"
  - "miscellaneous diagnostic dyes"
  - "miscellaneous diuretics"
  - "miscellaneous genitourinary tract agents"
  - "miscellaneous GI agents"
  - "miscellaneous hormones"
  - "miscellaneous metabolic agents"
  - "miscellaneous ophthalmic agents"
  - "miscellaneous otic agents"
  - "miscellaneous respiratory agents"
  - "miscellaneous sex hormones"
  - "miscellaneous topical agents"
  - "miscellaneous uncategorized agents"
  - "miscellaneous vaginal agents"
  - "mitotic inhibitors"
  - "monoamine oxidase inhibitors"
  - "mouth and throat products"
  - "mTOR inhibitors"
  - "mucolytics"
  - "multikinase inhibitors"
  - "muscle relaxants"
  - "mydriatics"
  - "narcotic analgesic combinations"
  - "narcotic analgesics"
  - "nasal anti-infectives"
  - "nasal antihistamines and decongestants"
  - "nasal lubricants and irrigations"
  - "nasal preparations"
  - "nasal steroids"
  - "natural penicillins"
  - "neprilysin inhibitors"
  - "neuraminidase inhibitors"
  - "neuromuscular blocking agents"
  - "neuronal potassium channel openers"
  - "next generation cephalosporins"
  - "nicotinic acid derivatives"
  - "NK1 receptor antagonists"
  - "NNRTIs"
  - "non-cardioselective beta blockers"
  - "non-iodinated contrast media"
  - "non-ionic iodinated contrast media"
  - "non-sulfonylureas"
  - "nonsteroidal anti-inflammatory agents"
  - "NS5A inhibitors"
  - "nucleoside reverse transcriptase inhibitors (NRTIs)"
  - "nutraceutical products"
  - "nutritional products"
  - "ophthalmic anesthetics"
  - "ophthalmic anti-infectives"
  - "ophthalmic anti-inflammatory agents"
  - "ophthalmic antihistamines and decongestants"
  - "ophthalmic diagnostic agents"
  - "ophthalmic glaucoma agents"
  - "ophthalmic lubricants and irrigations"
  - "ophthalmic preparations"
  - "ophthalmic steroids"
  - "ophthalmic steroids with anti-infectives"
  - "ophthalmic surgical agents"
  - "oral nutritional supplements"
  - "other immunostimulants"
  - "other immunosuppressants"
  - "otic anesthetics"
  - "otic anti-infectives"
  - "otic preparations"
  - "otic steroids"
  - "otic steroids with anti-infectives"
  - "oxazolidinedione anticonvulsants"
  - "oxazolidinone antibiotics"
  - "parathyroid hormone and analogs"
  - "PCSK9 inhibitors"
  - "penicillinase resistant penicillins"
  - "penicillins"
  - "peripheral opioid receptor antagonists"
  - "peripheral vasodilators"
  - "peripherally acting antiobesity agents"
  - "phenothiazine antiemetics"
  - "phenothiazine antipsychotics"
  - "phenylpiperazine antidepressants"
  - "phosphate binders"
  - "plasma expanders"
  - "platelet aggregation inhibitors"
  - "platelet-stimulating agents"
  - "polyenes"
  - "potassium sparing diuretics with thiazides"
  - "potassium-sparing diuretics"
  - "probiotics"
  - "progesterone receptor modulators"
  - "progestins"
  - "prolactin inhibitors"
  - "prostaglandin D2 antagonists"
  - "protease inhibitors"
  - "protease-activated receptor-1 antagonists"
  - "proteasome inhibitors"
  - "proton pump inhibitors"
  - "psoralens"
  - "psychotherapeutic agents"
  - "psychotherapeutic combinations"
  - "purine nucleosides"
  - "pyrrolidine anticonvulsants"
  - "quinolones"
  - "radiocontrast agents"
  - "radiologic adjuncts"
  - "radiologic agents"
  - "radiologic conjugating agents"
  - "radiopharmaceuticals"
  - "recombinant human erythropoietins"
  - "renin inhibitors"
  - "respiratory agents"
  - "respiratory inhalant products"
  - "rifamycin derivatives"
  - "salicylates"
  - "sclerosing agents"
  - "second generation cephalosporins"
  - "selective estrogen receptor modulators"
  - "selective immunosuppressants"
  - "selective phosphodiesterase-4 inhibitors"
  - "selective serotonin reuptake inhibitors"
  - "serotonin-norepinephrine reuptake inhibitors"
  - "serotoninergic neuroenteric modulators"
  - "sex hormone combinations"
  - "sex hormones"
  - "SGLT-2 inhibitors"
  - "skeletal muscle relaxant combinations"
  - "skeletal muscle relaxants"
  - "smoking cessation agents"
  - "somatostatin and somatostatin analogs"
  - "spermicides"
  - "statins"
  - "sterile irrigating solutions"
  - "streptomyces derivatives"
  - "succinimide anticonvulsants"
  - "sulfonamides"
  - "sulfonylureas"
  - "synthetic ovulation stimulants"
  - "tetracyclic antidepressants"
  - "tetracyclines"
  - "therapeutic radiopharmaceuticals"
  - "therapeutic vaccines"
  - "thiazide diuretics"
  - "thiazolidinediones"
  - "thioxanthenes"
  - "third generation cephalosporins"
  - "thrombin inhibitors"
  - "thrombolytics"
  - "thyroid drugs"
  - "TNF alfa inhibitors"
  - "tocolytic agents"
  - "topical acne agents"
  - "topical agents"
  - "topical anesthetics"
  - "topical anti-infectives"
  - "topical anti-rosacea agents"
  - "topical antibiotics"
  - "topical antifungals"
  - "topical antihistamines"
  - "topical antineoplastics"
  - "topical antipsoriatics"
  - "topical antivirals"
  - "topical astringents"
  - "topical debriding agents"
  - "topical depigmenting agents"
  - "topical emollients"
  - "topical keratolytics"
  - "topical non-steroidal anti-inflammatories"
  - "topical photochemotherapeutics"
  - "topical rubefacient"
  - "topical steroids"
  - "topical steroids with anti-infectives"
  - "triazine anticonvulsants"
  - "tricyclic antidepressants"
  - "trifunctional monoclonal antibodies"
  - "ultrasound contrast media"
  - "upper respiratory combinations"
  - "urea anticonvulsants"
  - "urea cycle disorder agents"
  - "urinary anti-infectives"
  - "urinary antispasmodics"
  - "urinary pH modifiers"
  - "uterotonic agents"
  - "vaccine combinations"
  - "vaginal anti-infectives"
  - "vaginal preparations"
  - "vasodilators"
  - "vasopressin antagonists"
  - "vasopressors"
  - "VEGF/VEGFR inhibitors"
  - "viral vaccines"
  - "viscosupplementation agents"
  - "vitamin and mineral combinations"
  - "vitamins"
