---
  -
    name: "Pre-MDC"
    code: "0"
  -
    name: "Diseases and Disorders of the Nervous System"
    code: "1"
  -
    name: "Diseases and Disorders of the Eye"
    code: "2"
  -
    name: "Diseases and Disorders of the Ear, Nose, Mouth And Throat"
    code: "3"
  -
    name: "Diseases and Disorders of the Respiratory System"
    code: "4"
  -
    name: "Diseases and Disorders of the Circulatory System"
    code: "5"
  -
    name: "Diseases and Disorders of the Digestive System"
    code: "6"
  -
    name: "Diseases and Disorders of the Hepatobiliary System And Pancreas"
    code: "7"
  -
    name: "Diseases and Disorders of the Musculoskeletal System And Connective Tissue"
    code: "8"
  -
    name: "Diseases and Disorders of the Skin, Subcutaneous Tissue And Breast"
    code: "9"
  -
    name: "Diseases and Disorders of the Endocrine, Nutritional And Metabolic System"
    code: "10"
  -
    name: "Diseases and Disorders of the Kidney And Urinary Tract"
    code: "11"
  -
    name: "Diseases and Disorders of the Male Reproductive System"
    code: "12"
  -
    name: "Diseases and Disorders of the Female Reproductive System"
    code: "13"
  -
    name: "Pregnancy, Childbirth And Puerperium"
    code: "14"
  -
    name: "Newborn And Other Neonates (Perinatal Period)"
    code: "15"
  -
    name: "Diseases and Disorders of the Blood and Blood Forming Organs and Immunological Disorders"
    code: "16"
  -
    name: "Myeloproliferative DDs (Poorly Differentiated Neoplasms)"
    code: "17"
  -
    name: "Infectious and Parasitic DDs (Systemic or unspecified sites)"
    code: "18"
  -
    name: "Mental Diseases and Disorders"
    code: "19"
  -
    name: "Alcohol/Drug Use or Induced Mental Disorders"
    code: "20"
  -
    name: "Injuries, Poison And Toxic Effect of Drugs"
    code: "21"
  -
    name: "Burns"
    code: "22"
  -
    name: "Factors Influencing Health Status and Other Contacts with Health Services"
    code: "23"
  -
    name: "Multiple Significant Trauma"
    code: "24"
  -
    name: "Human Immunodeficiency Virus Infection"
    code: "25"
